using Microsoft.AspNetCore.SignalR;
using MatchMakingService.Application.Constants;
using MatchMakingService.Application.Interfaces;

namespace MatchMakingService.Hubs;

public class LobbyHub(ILobbyService lobbyService, ILogger<LobbyHub> logger) : Hub
{
    public override Task OnConnectedAsync()
    {
        logger.LogInformation("Client connected: {ContextConnectionId}", Context.ConnectionId);
        return base.OnConnectedAsync();
    }

    public override async Task OnDisconnectedAsync(Exception? exception)
    {
        logger.LogInformation("Client disconnected: {ContextConnectionId}", Context.ConnectionId);
        await lobbyService.LeaveLobbyAsync(Context.ConnectionId);
        await base.OnDisconnectedAsync(exception);
    }

    public async Task CreateLobbyAsync(string lobbyName, int maxPlayers, string userName)
    {
        var result = await lobbyService.CreateLobbyAsync(lobbyName, maxPlayers, Context.ConnectionId, userName);
        if (!result.IsSuccessful)
        {
            await Clients.Caller.SendAsync(SignalRConstants.OnLobbyCreationFailed, "Failed to create lobby");
            return;
        }

        var lobby = result.Value!;
        
        await Groups.AddToGroupAsync(Context.ConnectionId, lobby.Code);
        await Clients.Caller.SendAsync(SignalRConstants.OnLobbyCreated, lobby.Code, lobby.Name);
        logger.LogInformation("Lobby with name: {LobbyName} and code: {LobbyCode} is generated by: {UserName} from connection id: {ContextConnectionId}", lobby.Name, lobby.Code, userName, Context.ConnectionId);
    }

    public async Task JoinLobbyAsync(string lobbyCode, string userName)
    {
        var result = await lobbyService.JoinLobbyAsync(lobbyCode, Context.ConnectionId, userName);
        if (!result.IsSuccessful)
        {
            await Clients.Caller.SendAsync(SignalRConstants.OnPlayerJoinFailed, result.ErrorMessage ?? "Failed to join lobby - Unknown error");
            return;
        }

        var lobby = result.Value!;
        
        await Groups.AddToGroupAsync(Context.ConnectionId, lobby.Code);
        await Clients.Caller.SendAsync(SignalRConstants.OnLobbyJoined, lobby.Code, lobby.Name);
        await Clients.GroupExcept(
            lobbyCode,
            Context.ConnectionId).SendAsync(SignalRConstants.OnPlayerJoined, lobby.Players);

        if (lobby.IsFull)
        {
            await Clients.Caller.SendAsync(SignalRConstants.OnLobbyFull, lobby.Code, lobby.Players);
        }
    }
}