using Microsoft.AspNetCore.SignalR;
using MatchMakingService.Application.Interfaces;

namespace MatchMakingService.Hubs;

public class LobbyHub(ILobbyService lobbyService, ILogger<LobbyHub> logger) : Hub
{
    public override Task OnConnectedAsync()
    {
        logger.LogInformation("Client connected: {ContextConnectionId}", Context.ConnectionId);
        return base.OnConnectedAsync();
    }

    public override async Task OnDisconnectedAsync(Exception? exception)
    {
        logger.LogInformation("Client disconnected: {ContextConnectionId}", Context.ConnectionId);
        await lobbyService.LeaveLobbyAsync(Context.ConnectionId);
        await base.OnDisconnectedAsync(exception);
    }

    public async Task CreateLobbyAsync(string lobbyName, int maxPlayers, string userName)
    {
        var result = await lobbyService.CreateLobbyAsync(lobbyName, maxPlayers, Context.ConnectionId, userName);
        if (!result.IsSuccessful)
        {
            logger.LogError("Failed to create lobby: {ErrorMessage}", result.ErrorMessage ?? "Unknown error!");
            return;
        }

        var lobby = result.Value!;
        logger.LogInformation("Lobby with name: {LobbyName} and code: {LobbyCode} is generated by: {UserName} from connection id: {ContextConnectionId}", lobby.Name, lobby.Code, userName, Context.ConnectionId);
    }

    public async Task JoinLobbyAsync(string lobbyCode, string userName)
    {
        var result = await lobbyService.JoinLobbyAsync(lobbyCode, Context.ConnectionId, userName);
        if (!result.IsSuccessful)
        {
            logger.LogError("Failed to join lobby: {ErrorMessage}", result.ErrorMessage ?? "Failed to join lobby - Unknown error");
            return;
        }

        var lobby = result.Value!;
        logger.LogInformation("Lobby with code: {LobbyCode} and user: {UserName}", lobby.Code, userName);
    }

    public async Task LeaveLobbyAsync(string lobbyCode)
    {
        await RemoveConnectionFromLobby(lobbyCode, Context.ConnectionId);
    }

    public async Task KickUserAsync(string lobbyCode, string connectionId)
    {
        await RemoveConnectionFromLobby(lobbyCode, connectionId);
    }

    private async Task RemoveConnectionFromLobby(string lobbyCode, string connectionId)
    {
        var result = await lobbyService.LeaveLobbyAsync(lobbyCode, connectionId);
        if (!result.IsSuccessful)
        {
            logger.LogError("Failed to leave lobby: {ErrorMessage}", result.ErrorMessage ?? "Unknown error!");
            return;
        }
        
        logger.LogInformation("Lobby with code: {LobbyCode} and connection id: {ConnectionId} has left the room!", lobbyCode, Context.ConnectionId);
    }
}